{
 "title": "Graphcast Subgraph Radio",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "POI Comparison Overview",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "resultType",
     "queryText": "query {\n  data:comparisonResults{\n    deployment\n    resultType\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Message stats",
   "type": "stat",
   "description": "Average metrics based on each scrape\n- counter for received valid messages\n- gauge of cached messages\n\n- cached messages \n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphcast_subgraph_radio_validated_messages{}[30m])) * 60",
     "legendFormat": "Messages Validated/Minute"
    },
    {
     "expr": "sum(graphcast_subgraph_radio_cached_ppoi_messages{})",
     "legendFormat": "Messages In Store"
    },
    {
     "expr": "sum(graphcast_subgraph_radio_received_messages)",
     "legendFormat": "Received Messages"
    }
   ]
  },
  {
   "title": "Number of Gossiping Indexers per Subgraph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_connected_peers"
    },
    {
     "expr": "graphcast_subgraph_radio_gossip_peers"
    }
   ]
  },
  {
   "title": "POI Comparison Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "null",
     "queryText": "query {\n  data:comparisonRatio{\n    deployment\n    blockNumber\n    senderRatio\n    stakeRatio\n   allocated\n}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Average Message Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(graphcast_subgraph_radio_cached_ppoi_messages[ $__rate_interval ])"
    }
   ]
  },
  {
   "title": "Number of diverged subgraphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_diverging_subgraphs"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_average_processing_time"
    }
   ]
  },
  {
   "title": "Frequent Senders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(graphcast_subgraph_radio_frequent_senders[$__interval])) by (indexer_address))"
    }
   ]
  },
  {
   "title": "Max Stake POI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_attested_max_stake_weight"
    }
   ]
  },
  {
   "title": "Latest Message Timestamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_latest_message_timestamp"
    }
   ]
  },
  {
   "title": "Function Call Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "function_calls_concurrent" },
    {
     "expr": "histogram_quantile(0.95, sum(rate(function_calls_duration_bucket[5m])) by (le))"
    },
    { "expr": "rate(function_calls_count[5m])" }
   ]
  }
 ]
}