[package]
name = "test-utils"
version = "0.0.1"
edition = "2021"
authors = ["GraphOps (axiomatic-aardvark, hopeyen)"]
description = "Subgraph Radio e2e tests"
license = "Apache-2.0"
repository = "https://github.com/graphops/subgraph-radio"
keywords = [
    "graphprotocol",
    "data-integrity",
    "Indexer",
    "waku",
    "p2p",
    "tests",
]
categories = [
    "network-programming",
    "web-programming::http-client",
    "e2e-tests",
]

[dependencies]
waku = { version = "0.1.1", package = "waku-bindings" }
graphcast-sdk = "0.4.1"
subgraph-radio = { path = "../subgraph-radio" }
tokio = { version = "1.1.1", features = ["full", "rt"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8.3"
chrono = "0.4"
axum = "0.5"
tower-http = { version = "0.4.0", features = ["trace", "cors"] }
tower = "0.4.13"
uuid = "1.3.3"
serde = { version = "1.0.163", features = ["rc"] }
serde_json = "1.0.96"
serde_derive = "1.0"
clap = { version = "3.2.25", features = ["derive"] }
prost = "0.11"
ethers = "2.0.4"
ethers-contract = "2.0.4"
ethers-core = "2.0.4"
ethers-derive-eip712 = "1.0.2"
async-graphql = "4.0.16"
